### ISSUE TITLE
Implementing Turtlebot Navigation in Custom World

### ISSUE THREAD

**Issue by curious-vv1** [OPCODE-Open-Spring-Fest/turtlebot-navigation#4]
### So, what is it about?

In the turtle_ws/src/turtlebot3_gazebo/worlds directory, we have a custom world file named maze.world. The objective is to develop a Python script, maze.py, in scripts folder(make a folder named scripts) within turtle_ws/src, to facilitate Turtlebot navigation within this maze-like environment. The Turtlebot should navigate from the initial coordinate (0,3) to the destination coordinate (3,-3) while effectively avoiding obstacles. You are free to use Waypoint Navigation or Go To Pose Navigation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kumar-ujjawal** [comment]
Assign me this issue to I have knowledge of ros2 and navigation.

**Comment by curious-vv1** [comment]
Ok @Kumar-ujjawal you have been assigned this issue. You can make pull requests within 16 working hours.
